#include "cbase.h"
#include "scaleformcomponent_common.h"

// memdbgon must be the last include file in a .cpp file!!!
#include "tier0/memdbgon.h"

UI_COMPONENT_DEFINE_EVENT(Blog, HideBlog);
UI_COMPONENT_DEFINE_EVENT(Blog, ShowBlog);
UI_COMPONENT_DEFINE_EVENT(Device, Reset);
UI_COMPONENT_DEFINE_EVENT(Device, Tick);
UI_COMPONENT_DEFINE_EVENT(EmbeddedStream, VideoPlaying);
UI_COMPONENT_DEFINE_EVENT(EmbeddedStream, VolumeChanged);
UI_COMPONENT_DEFINE_EVENT(FriendsList, NameChanged);
UI_COMPONENT_DEFINE_EVENT(FriendsList, ProfileUpdated);
UI_COMPONENT_DEFINE_EVENT(FriendsList, RebuildFriendsList);
UI_COMPONENT_DEFINE_EVENT(GC, Hello);
UI_COMPONENT_DEFINE_EVENT(GlobalGame, StateChange);
UI_COMPONENT_DEFINE_EVENT(ImageCache, PurgePassEnd);
UI_COMPONENT_DEFINE_EVENT(ImageCache, PurgePassStart);
UI_COMPONENT_DEFINE_EVENT(Inventory, CrateOpened);
UI_COMPONENT_DEFINE_EVENT(Inventory, ModelPanelReady);
UI_COMPONENT_DEFINE_EVENT(Inventory, OnHasNewItems);
UI_COMPONENT_DEFINE_EVENT(Inventory, WeaponPreviewRequest);
UI_COMPONENT_DEFINE_EVENT(Leaderboards, StateChange);
UI_COMPONENT_DEFINE_EVENT(MatchInfo, StateChange);
UI_COMPONENT_DEFINE_EVENT(MatchList, FantasyUploaded);
UI_COMPONENT_DEFINE_EVENT(MatchList, PredictionUploaded);
UI_COMPONENT_DEFINE_EVENT(MatchList, StateChange);
UI_COMPONENT_DEFINE_EVENT(MyPersona, AccountPrivacySettingsChanged);
UI_COMPONENT_DEFINE_EVENT(MyPersona, ClientAuthKeyCode);
UI_COMPONENT_DEFINE_EVENT(MyPersona, ElevatedStateUpdate);
UI_COMPONENT_DEFINE_EVENT(MyPersona, InventoryUpdated);
UI_COMPONENT_DEFINE_EVENT(MyPersona, InventoryUpdatedImmediate);
UI_COMPONENT_DEFINE_EVENT(MyPersona, MedalsChanged);
UI_COMPONENT_DEFINE_EVENT(MyPersona, NameChanged);
UI_COMPONENT_DEFINE_EVENT(News, BlogUpdate);
UI_COMPONENT_DEFINE_EVENT(Overwatch, CaseUpdated);
UI_COMPONENT_DEFINE_EVENT(PartyBrowser, InviteConsumed);
UI_COMPONENT_DEFINE_EVENT(PartyBrowser, InviteReceived);
UI_COMPONENT_DEFINE_EVENT(PartyBrowser, Refresh);
UI_COMPONENT_DEFINE_EVENT(PartyList, MatchmakingSessionUpdate);
UI_COMPONENT_DEFINE_EVENT(PartyList, RebuildPartyList);
UI_COMPONENT_DEFINE_EVENT(Store, PriceSheetChanged);
UI_COMPONENT_DEFINE_EVENT(Store, PurchaseCompleted);
UI_COMPONENT_DEFINE_EVENT(Store, UpdateStoreTiles);
UI_COMPONENT_DEFINE_EVENT(Streams, MyTwitchTvStateUpdate);
UI_COMPONENT_DEFINE_EVENT(Streams, PreviewImageUpdate);
UI_COMPONENT_DEFINE_EVENT(Streams, Update);
UI_COMPONENT_DEFINE_EVENT(Teammates, Refresh);
UI_COMPONENT_DEFINE_EVENT(TournamentMatch, DraftUpdate);
UI_COMPONENT_DEFINE_EVENT(UGC, DownloadingStateUpdate);